### PR TITLE
Feat/billboard

### PR DESCRIPTION
**Pull request by JemalSmb**
Billboard page up and running.
Ok to merge with main.

### CODE REVIEW

**Review by JemalSmb — COMMENTED** [review]
Changed ads api endpoint to the correct one

**Review by JemalSmb — COMMENTED** [review]
Chnaged the route path in the APP to match the path in the sidebar

**Review by JemalSmb — COMMENTED** [review]
Per our discussion, switched code from the LiveAds to billboard because it made more sense

**Review by shnartho — APPROVED** [review]

**Comment by shnartho** [comment]
> Per our discussion, switched code from the LiveAds to billboard because it made more sense

looks good now👍

**Pull request merged**
